'use client'
import Link from 'next/link'
import { useSearchParams } from 'next/navigation'
import { HCP_INDICATORS } from '@/lib/data/hcp-indicators'
import { Suspense, useMemo, useState } from 'react'
const labels: Record<string,string> = { economy:'الاقتصاد والتجارة', society:'المجتمع', education:'التعليم والثقافة', health:'الصحة', employment:'الشغل', population:'السكان والديموغرافيا' }
const englishDomains: Record<string,string> = { 'الاقتصاد والتجارة':'Economy','المال والأسواق':'Money & Markets','المجتمع':'Society','الفقر وعدم المساواة':'Poverty & Inequality','التعليم والثقافة':'Education','الصحة':'Health','الشغل':'Employment','السكان والديموغرافيا':'Population & Demography','العدالة والمجتمع':'Justice & Society' }
function EnglishCatalog(){ const params=useSearchParams(); const [query,setQuery]=useState(''); const active=labels[params.get('domain')||'']; const items=useMemo(()=>HCP_INDICATORS.filter(i=>(!active||i.domain===active)&&`${i.frenchTitle} ${i.arabicTitle} ${i.id} ${i.domain} ${i.source}`.toLowerCase().includes(query.toLowerCase())),[active,query]); const groups=[...new Set(items.map(i=>i.domain))]; return <main dir="ltr" lang="en" className="catalog-page"><header className="catalog-header"><div className="catalog-shell"><Link className="catalog-back" href="/en">← Back home</Link><p className="eyebrow">National Observatory of Moroccan Indicators</p><h1>All indicators</h1><p>Explore indicators from official sources.</p><div className="catalog-count">{items.length} of {HCP_INDICATORS.length} indicators</div></div></header><section className="catalog-shell catalog-tools"><label className="catalog-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search indicators..." aria-label="Search indicators" /></label></section><section className="catalog-shell catalog-results">{groups.map(group=><div className="catalog-group" key={group}><div className="catalog-group-heading"><span>DATA DOMAIN</span><h2>{englishDomains[group]||group}</h2></div><div className="catalog-grid">{items.filter(i=>i.domain===group).map(i=><Link className="catalog-card" href={`/en/indicators/${i.id}`} key={i.id}><span className="catalog-domain">{englishDomains[i.domain]||i.domain}</span><h3>{i.frenchTitle}</h3><div><b>{i.id}</b><span>Open indicator →</span></div></Link>)}</div></div>)}</section></main> }
export default function Page(){ return <Suspense fallback={<main className="catalog-page"><div className="catalog-shell catalog-empty">Loading indicators...</div></main>}><EnglishCatalog /></Suspense> }
