import Link from 'next/link'
import { getIndicator } from '@/lib/data/hcp-indicators'
import { fetchIndicator, latestObservation } from '@/lib/data/hcp'
import IndicatorVisuals from '@/components/indicator-visuals'

export default async function IndicatorDetailPage({ id }: { id: string }) {
  const debugIndicators = process.env.NEXT_PUBLIC_DEBUG_INDICATORS === 'true'
  const indicator = getIndicator(id)
  if (!indicator) return <main dir="rtl" className="detail-page"><div className="detail-shell"><Link className="back-link" href="/#indicators">← العودة إلى المؤشرات</Link><div className="empty-state"><p className="eyebrow">المرصد الوطني للمؤشرات</p><h1>المؤشر غير موجود</h1><p>لم يتم العثور على هذا المؤشر في قاعدة البيانات.</p></div></div></main>
  const data = await fetchIndicator(indicator)
  if (!data.normalized) return <main dir="rtl" className="detail-page"><div className="detail-shell"><Link className="back-link" href="/#indicators">← العودة إلى المؤشرات</Link><div className="empty-state"><p className="eyebrow">{data.error === 'integrity' ? 'سلامة البيانات' : 'مصدر البيانات'}</p><h1>{data.error === 'integrity' ? 'خطأ في مطابقة البيانات' : 'تعذر الوصول إلى مصدر البيانات'}</h1><p>{data.error === 'integrity' ? 'تعذر التأكد من أن البيانات تخص هذا المؤشر.' : data.endpoint}</p>{debugIndicators && <pre className="debug-panel">{JSON.stringify({ requestedId: indicator.id, apiUrl: data.endpoint, responseCode: data.responseCode, apiLabel: data.responseLabel, registryArabicTitle: indicator.arabicTitle, registryFrenchTitle: indicator.frenchTitle, displayedArabicTitle: indicator.arabicTitle, metadataIntegrity: data.integrity.metadataValid ? 'VALID' : 'MISMATCH', dataIntegrity: data.integrity.dataValid ? 'VALID' : data.integrity.reason, cacheKey: data.cacheKey || `indicator-data-${indicator.id}`, routeId: id, integrity: data.integrity.valid ? 'VALID' : data.integrity.reason }, null, 2)}</pre>}</div></div></main>
  const normalized = data.normalized
  const rows = normalized.observations.filter((row) => row.value !== null).sort((a, b) => Number(a.period) - Number(b.period))
  const latest = latestObservation(normalized)
  const latestValue = latest?.value !== null && latest?.value !== undefined ? String(latest.value) : rows.length ? 'اختر الأبعاد' : 'البيانات غير متاحة'
  return <main dir="rtl" className="detail-page"><div className="detail-shell"><div className="detail-actions"><Link className="back-link" href="/#indicators">← العودة إلى المؤشرات</Link><Link className="language-switch" href={`/en/indicators/${id}`}>EN</Link></div><header className="detail-header"><p className="eyebrow">مؤشر {indicator.id}</p><h1>{indicator.arabicTitle}</h1><p className="detail-definition">{indicator.description}</p><p className="detail-meta">{indicator.frenchTitle} · {indicator.id}</p>{debugIndicators && <pre className="debug-panel">{JSON.stringify({ requestedId: indicator.id, apiUrl: data.endpoint, responseCode: data.responseCode, apiLabel: data.responseLabel, registryArabicTitle: indicator.arabicTitle, registryFrenchTitle: indicator.frenchTitle, displayedArabicTitle: indicator.arabicTitle, metadataIntegrity: data.integrity.metadataValid ? 'VALID' : 'MISMATCH', dataIntegrity: data.integrity.dataValid ? 'VALID' : data.integrity.reason, cacheKey: data.cacheKey || `indicator-data-${indicator.id}`, routeId: id, integrity: data.integrity.valid ? 'VALID' : data.integrity.reason }, null, 2)}</pre>}</header><div className="gold-rule" /><section className="latest-grid"><div><p className="eyebrow">أحدث قيمة منشورة</p><strong className="latest-value">{latestValue}</strong><p>آخر قيمة منشورة · {latest?.period || '—'}</p><p className="context-sentence">تشير البيانات إلى قيمة تبلغ {latestValue} في آخر سنة متاحة.</p></div><dl><div><dt>المصدر</dt><dd>{normalized.metadata.source || 'المندوبية السامية للتخطيط'}</dd></div><div><dt>الوحدة</dt><dd>{normalized.metadata.unit || '—'}</dd></div><div><dt>التواتر</dt><dd>{normalized.metadata.frequency || '—'}</dd></div></dl></section><section className="detail-section visual-section"><p className="eyebrow">شرح بصري</p><h2>ماذا حدث؟</h2><IndicatorVisuals key={indicator.id} rows={rows} dimensions={normalized.dimensions} unit={normalized.metadata.unit} indicatorId={indicator.id} /></section><details className="detail-section data-details"><summary><span><p className="eyebrow">الشفافية</p><h2>عرض البيانات التفصيلية</h2></span><b>＋</b></summary><div className="table-wrap">{rows.length ? <table><thead><tr><th>الفترة</th><th>القيمة</th><th>الأبعاد</th></tr></thead><tbody>{rows.map((row) => <tr key={`${indicator.id}-${row.period}-${JSON.stringify(row.dimensionIds)}`}><td>{row.period}</td><td>{row.value}</td><td>{Object.values(row.dimensions).join(' · ') || 'وطني'}</td></tr>)}</tbody></table> : <p className="empty-copy">البيانات غير متاحة.</p>}</div></details><section className="source-section"><p className="eyebrow">مصدر البيانات</p><h2>المندوبية السامية للتخطيط</h2><p>المؤشر: {normalized.indicatorId || indicator.id}</p><a href={data.endpoint} target="_blank" rel="noreferrer">عرض المصدر الأصلي ↗</a></section></div></main>
}
